services:
  - type: web
    name: todo-web-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: FLASK_ENV
        value: production
